### ISSUE TITLE
Behavior for deselecting map

### ISSUE THREAD

**Issue by oevans** [Esri/Compare-Maps-Template#1]
If I have a map selected and then go into the web map picker and click on that map again, nothing happens visually (it still appears selected). However, I noticed that the configuration panel then reports an additional map is currently displayed.  When saving the configuration the clicked map then appears twice (see screenshot).

If I hold Command and click the map, then it is deselected and removed from the app configuration.

I'm using Safari 8.0 on Mac OS X 10.10.1.

![screen shot 2014-12-11 at 10 38 09 am](https://cloud.githubusercontent.com/assets/3215530/5396679/1a2dd392-8122-11e4-8e33-19e34bc35917.png)

**Comment by kellyhutchins** [comment]
@oevans  this is also fixed for the next release (late March).
