### ISSUE TITLE
no compare in live sample

### ISSUE THREAD

**Issue by upcamogie** [Esri/Compare-Maps-Template#11]
i wanted to see how the compare worked but there is only one map in the live sample
- when i download the code and add my 2 web maps, there are 3 panels that appear. There is a 'farmers market' webmap that is included but I do not have it listed in my web map list in index.html. where else are web maps referenced? I am not  a developer so I appreciate better documentation and explanation with thees samples

**Comment by kellyhutchins** [comment]
You'll need to replace the default web map  id (Farmer's Market)  in the /config/defaults.js file with your own web map id.

**Comment by upcamogie** [comment]
I did-- in my default.js i have this line
 "appid": "",
    "webmap": "",
    "webmaps": ["3bf188bbbd5442dbb8922163a188311b", "b82080dd9abd4ec4a3bc18cbfb373d1d",],

these are my 2 maps listed but i see 3 panels.....what am i missing?

**Comment by kellyhutchins** [comment]
Looks like you have an extra comma after the last web map in the web maps array that might be causing a problem. Try this instead. 

"appid": "",
"webmap": "3bf188bbbd5442dbb8922163a188311b",
"webmaps": ["b82080dd9abd4ec4a3bc18cbfb373d1d"],

**Comment by upcamogie** [comment]
thanks.
The extra comma did not matter, but what matters is the code you sent. I did not realize that if you left the webmap parameter blank,it defaults to a farmers market map.....not very helpful to have a blank value that really does have a value. But if I add my one map in webmap and the second under 'webmaps' I have success. 
I am new to these resources, confusing to have something with default. you may want to very explicitly state that farmers market is a web map that will appear unless you change the webmap tag and not the webmaps. For a novice like me, reading this means if i want a single map i use webmap and for more than one i list them under 'webmaps.'

also, what is the point of the left panel other than the map title? i guess description if there is one? In other web apps, that space takes the web map description, here it does not. 
thanks again for the response. keep the samples coming.....especially if you ever get related tables to work in web apps (and i dont mean WAB)

**Comment by kellyhutchins** [comment]
@upcamogie  thanks for the feedback. We originally had the web map desc in the side panel but when comparing more than two maps it got very cluttered so we kept it as an area to hold contextual info about the app. If you don't want the side panel at all you can turn it off by setting showTitleAndDescription to false in the defaults.js file. 

I'll work on adding some notes to the defaults.js file to try and make it more clear how to set multiple web maps. 

There's a javascript code sample here that shows how to display related records that might help. https://geonet.esri.com/thread/121633

**Comment by upcamogie** [comment]
Info about the app is good...is there a limit on how much info you can add in this description area? can you add hyperlinks? formatting? 

Thanks for the related records link....code sample looks good for someone who knows how to read it, ha. I understand the basics but unless its in an app already I have no idea on how to add this to an existing app (all of my apps are downloaded from here that i tweak ever so slightly)

**Comment by kellyhutchins** [comment]
You can add hyperlinks and formatting to the description panel. When you configure this template the info for the description panel uses whatever you enter in the 'Details' text area in the 'Side Panel Settings' section. The text editor for the 'Details' section allows you to do some minor formatting like color changes, bold, italic, underline, hyperlinks, insert image and bullets. 

We do want to add related records support to one of the templates but no concrete plans yet for which one. Perhaps for the next release we'll have that capability added to one.
