### ISSUE TITLE
please add ability to add logo

### ISSUE THREAD

**Issue by upcamogie** [Esri/Compare-Maps-Template#12]
it would help with branding and consistency if my web apps could have same color and logo options.

**Comment by kellyhutchins** [comment]
@upcamogie you could add the logo to the description that displays in the side panel.  For this request would you want the logo to appear on the map?

**Comment by upcamogie** [comment]
On the map would be good. I have seen it added to bottom right, i changed to top right as this works better for me. As long as there is somewhere i can add a logo and then decide where to place it, I think it would be good. thanks

**Comment by kellyhutchins** [comment]
Ok I'll add an enhancement for the next release.

**Comment by upcamogie** [comment]
I am working on a locally hosted version, id definitely appreciate the instructions on how to do this. thanks!

**Comment by kellyhutchins** [comment]
Here's info on how to add a custom logo. All edits occur in the main.js file. 

1. First we'll turn off the esri logo. You can do this by searching main.js for arcgisUtils.createMap. Its at approximately line 111.  Update this code to set the logo to false by adding the mapOptions bit. 
                var def = arcgisUtils.createMap(this.config.webmaps[i], cell.id, {
                    mapOptions:{
                        logo:false
                    },
                    usePopupManager: true,
                    editable: this.config.editable,
                    bingMapsKey: this.config.bingKey
                });

2. Next add your custom logo image and link. You can add this code right after the line that sets the popup theme (domClass.add(result.map.infoWindow.domNode, "light"). 
                        query("#map_" + i + " .esriControlsBR").forEach(lang.hitch(this, function (node) {
                            //add a custom logo link
                            var link = null;
                            link = domConstruct.create("a", {
                                href: "http://www.github.com", //url for your logo link. 
                                target: "_blank"
                            }, node);

                            //add a custom image 
                            var logoimg = domConstruct.create("img", {
                                width: "65px",
                                height: "36px",
                                src: "images/error.png",  //path to your custom logo image
                                "class": "logo"
                            }, link || node);
                        }));

**Comment by upcamogie** [comment]
thanks! going to try it now

**Comment by upcamogie** [comment]
it worked, thanks! i am undecided to have the logo on each panel of web map but its great to have the option. 

Another question (sorry for putting here, wasnt sure to add another issue), can the sync be set to automatically sync instead of having to activate on each map?

**Comment by kellyhutchins** [comment]
@upcamogie at this point sync can't be set automatically but its something we can look at for a future release.
