### ISSUE TITLE
change color of map description

### ISSUE THREAD

**Issue by upcamogie** [Esri/Compare-Maps-Template#13]
I have looked at all of the places in the main.css where I could think to change the color of the text in the side panel where the map description/legends are, but have no luck. I have everything else the way i want (black background, white text) but the description is still grey. Are there any further resources available for this app? thx

**Comment by kellyhutchins** [comment]
@upcamogie  there are a few ways you can do this. You can configure the application using the template configuration process and use the Details editing section to define custom text for the side panel. The editor provided on the config panel will let you set the text color. 
Once you've configured the app in online you can copy the application id from the url and paste it into the appid section of the deafults.js config file. 
![screen shot 2015-04-28 at 9 09 20 am](https://cloud.githubusercontent.com/assets/2124187/7374302/4b96d188-ed86-11e4-8878-a33e7568e27c.png)

Another option is to update the css file to set the color you want. To do this open main.css and look for the .headerInfo section. Add the color you'd like the text to be to this section. For example:

.headerInfo{
 color:#ff0000;
}
