### ISSUE TITLE
Add ability to consume rest services

### ISSUE THREAD

**Issue by pcsswamin** [Esri/Compare-Maps-Template#14]
Please add ability to consume ArcGIS Server Rest services. The usefulness of this template would be vastly increased

**Comment by kellyhutchins** [comment]
All of the templates are designed to work with an ArcGIS Online web map. The easiest way to work with your rest services is to add them to a web map in Online then use the web map id to display your data in the template. 

Also the result of createMap is a map that you can then update to add your own data using the map.addLayer method. 

Alternatively it is possible to customize the template to work with local copies of a web map. A web map is just a description of the  contents of the map. Here's some information that explains how to work with a local copy of a web map. 
https://github.com/Esri/Viewer/wiki/local-definition
