### ISSUE TITLE
where is compare multiple maps can see?

### ISSUE THREAD

**Issue by dyh333** [Esri/Compare-Maps-Template#19]
hi, @kellyhutchins .i download the repo and publish on localhost. but i am sorry to say that i can not find where is compare-multiple-maps? all what i saw as the below picture.

![image](https://cloud.githubusercontent.com/assets/1221313/20341092/95279f36-ac1f-11e6-8c06-83ceaae047c1.png)

**Comment by iwittenmyer** [comment]
By default this application includes a reference to one web map, if you want to view more than one you can do so by adding the web map ids to [line 23 of the defaults.js](https://github.com/Esri/Compare-Maps-Template/blob/master/config/defaults.js#L23) file and removing the existing map from line 22..  ere is an example that shows two maps.  It works best with 2-4 maps.

"webmap": "",
 "webmaps": ["2bc6e99fcb9640f0aa14aebcbcbaccd9","293416c5572c4de581d84b66e3e8484b" ],

**Comment by dyh333** [comment]
yeah, it works. thanks. @iwittenmyer
