### ISSUE TITLE
Add folder access to basemap picker

### ISSUE THREAD

**Issue by oevans** [Esri/Compare-Maps-Template#2]
It would be great to have access to select a folder in my content. Sometimes I know exactly where a map is stored, but am not able to recall enough about the name, tags or title to find it via search.

To avoid fetching folders whenever the picker is loaded maybe the user could select My Folders and then have the list of folders load.

**Comment by kellyhutchins** [comment]
@oevans  are you referring to the map picker on the configuration panel?

**Comment by oevans** [comment]
@kellyhutchins Yes, sorry for the confusing title. ;-) I was referring to the map (not basemap) picker in the config panel. It'd be helpful to be able to browse and select from a list of folders in My Content.

**Comment by kellyhutchins** [comment]
closing this issue here since it refers to the Map picker in the config panel.  Will look into adding this capability to the map picker in a future release.
