### ISSUE TITLE
Home button icons missing

### ISSUE THREAD

**Issue by oevans** [Esri/Compare-Maps-Template#3]
Home zoom control button icons are not loading.

Safari 8.0 on Mac OSX 10.10.1.

![screen shot 2014-12-11 at 10 48 02 am](https://cloud.githubusercontent.com/assets/3215530/5396852/5bf946d4-8123-11e4-9cf5-7d319b0f3fab.png)

**Comment by kellyhutchins** [comment]
Thanks we've fixed this for the next release (late March).
