### ISSUE TITLE
Add configuration option for width of side panel

### ISSUE THREAD

**Issue by oevans** [Esri/Compare-Maps-Template#5]
Provide a way to configure the width of the side panel.  If one or more of the web map titles are longer or if the map descriptions are long it is useful to expand the side panel so that the titles are more readable and/or more of the description appears without scrolling.  Also if there are images in the description they can easily be chopped off due to the width of the side panel.

**Comment by kellyhutchins** [comment]
@oevans  another good suggestion. I'll look into this for a future release.

**Comment by kellyhutchins** [comment]
Added an enhancement for this issue and will look at it for the next release.

**Comment by upcamogie** [comment]
related, I am working with the left panel to add a description-- i cannot get my formatted code (hyperlinks, mailto, logo, etc) work within the   "description": "",
does Esri have a reference/example anywhere on how to add formatted code to web app templates?

**Comment by kellyhutchins** [comment]
You can format it using html. One option would be to configure the template description using the configuration panel in online then  use the appid for the configured app in your locally hosted template. 

Here's an example of a formatted bit of text for the content pane: 
"description": "This is a sample app that compares multiple maps. You can configure this app to have <b>formatted</b> text, <a href='http://www.arcgis.com'>Hyperlinks</a><ul><li>lists</li><li>of</li><li>items</li></ul> and more.",

**Comment by upcamogie** [comment]
thanks, I have tried that, but when i have a formatted hyperlink, such as "description": "This is a sample app that compares multiple maps. You can configure this app to have <i>formatted</i> text or <a href="http://www.arcgis.com">Hyperlinks</a></p> and more.", it does not work.

 if i leave out the hyper link part i can get the text to format bold or italic, but cannot get anything with quotes to work. the example you have is good and varied but just copying it without the source code formatting  does not explain how it can work. perhaps there is another way to add hyperlinks an mailto: ? thx

**Comment by kellyhutchins** [comment]
Sorry looks like its confusing because the html tags rendered in my comment so you can't see how it should look. Let's see if this works

'    "description": "This is a sample app that compares multiple maps. You can configure this app to have <b>formatted</b> text, <a href='http://www.arcgis.com'>Hyperlinks</a><ul><li>lists</li><li>of</li><li>items</li></ul> and more.",'

**Comment by upcamogie** [comment]
it worked this time, thanks! Its the little things like this that drive me crazy. a good place to stop for the day, thanks again
