### ISSUE TITLE
Max number of maps?

### ISSUE THREAD

**Issue by oevans** [Esri/Compare-Maps-Template#7]
The [what's new help topic](http://doc.arcgis.com/en/arcgis-online/reference/whats-new.htm) indicates this template can be used to compare up to four maps, but I was able to add more than that...

![screen shot 2014-12-11 at 12 38 47 pm](https://cloud.githubusercontent.com/assets/3215530/5398706/aee34200-8132-11e4-85ef-f62e2c572f12.png)

**Comment by kellyhutchins** [comment]
Thanks yeah its a typo in the doc. You can compare an unlimited amount of maps. Although at some point the app becomes a bit unwieldy.
