### ISSUE TITLE
Map picker search box appearance

### ISSUE THREAD

**Issue by oevans** [Esri/Compare-Maps-Template#9]
(Using Safari 8.0.3 and Chrome 40.0.2214.111 on Mac OS 10.10.2)

Something seems to be wrong with the appearance of the search box in the configuration panel's map picker.

In Safari, there is no line around the area to define the search box, and when I enter text it is the same color as the background so is invisible. The text can be seen if I go back in to the search box and drag to select the invisible text. The functionality of the search bar doesn't seem to be affected.

Initial view:
![screen shot 2015-02-13 at 7 39 16 am](https://cloud.githubusercontent.com/assets/3215530/6187354/6f338324-b353-11e4-8337-ac2c1e3bed59.png)

After typing search text and executing search:
![screen shot 2015-02-13 at 7 40 48 am](https://cloud.githubusercontent.com/assets/3215530/6187375/af8465d8-b353-11e4-98be-ab8d4866ce53.png)

After selecting "invisible" text:
![screen shot 2015-02-13 at 7 40 39 am](https://cloud.githubusercontent.com/assets/3215530/6187369/9ac0d1cc-b353-11e4-9b8f-bd2bbbb56c43.png)

In Chrome, the text is visible, but the button to clear search text is missing. I can see the placeholder for this button if I tab over (blue box in screenshot below).
![screen shot 2015-02-13 at 7 45 48 am](https://cloud.githubusercontent.com/assets/3215530/6187438/8cae60ee-b354-11e4-896c-ac3dab00764c.png)

**Comment by kellyhutchins** [comment]
@oevans  I can't reproduce with Mac OSX 10.10 and the same version of Chrome or on my Windows 8 Virtual Machine with the same version of Chrome.  If you haven't already done so can you try clearing your cache and re-testing?
![screen shot 2015-03-04 at 9 03 50 am](https://cloud.githubusercontent.com/assets/2124187/6488612/7a53ca80-c24d-11e4-8968-fda7a23e61cd.png)

**Comment by oevans** [comment]
Just tested in Safari/Mac OS X and things seem just fine. Guess it was a fluke! Looks like this one can be closed.

**Comment by kellyhutchins** [comment]
Great - I love when problems disappear :)
